// ignore_for_file: avoid_print
// dart run tool/theme_registry_gen.dart
//
// 扫描 lib/ui/design_system/theme/ 子目录下所有带有 @GameTheme() 注解的 Dart 文件，
// 提取类名与 domain 字面量，同时：
//   1. 生成 theme_catalog.g.dart  ← 纯声明，无 import（part 文件规范）
//   2. 刷新 theme_catalog.dart 头部的 import 区段（BEGIN/END 锚行间）

import 'dart:io';

void main() async {
  final themeRoot = Directory('lib/ui/design_system/theme');

  final entries = <_ThemeEntry>[];

  await for (final entity in themeRoot.list(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;

    final filename = entity.uri.pathSegments.last;
    if (const {
      'app_theme.dart',
      'theme_catalog.dart',
      'theme_annotation.dart',
      'theme_catalog.g.dart',
      'theme_generator.dart',
    }.contains(filename))
      continue;

    final source = await entity.readAsString();
    if (!source.contains('@GameTheme()')) continue;

    final entry = _parseThemeFile(source, entity.path);
    if (entry != null) entries.add(entry);
  }

  if (entries.isEmpty) {
    print('[ThemeGen] 未发现任何 @GameTheme() 标注文件，退出。');
    return;
  }

  // 1. 写 .g.dart（纯声明，无 import）
  await _writeGeneratedFile(entries);

  // 2. 刷新 theme_catalog.dart 的 import 区段
  await _refreshCatalogImports(entries);

  print('[ThemeGen] 生成完成。共收录 ${entries.length} 个主题：');
  for (final e in entries) {
    print('  • ${e.className} (${e.domain})  →  ${e.importPath}');
  }
}

// ---------------------------------------------------------------------------

class _ThemeEntry {
  final String className;
  final String domain; // "universal" | "maimai" | "chunithm"
  final String importPath; // package:... 格式

  _ThemeEntry({
    required this.className,
    required this.domain,
    required this.importPath,
  });
}

_ThemeEntry? _parseThemeFile(String source, String filePath) {
  final classMatch = RegExp(
    r'@GameTheme\(\)\s+class\s+(\w+)\s+extends\s+AppTheme',
  ).firstMatch(source);
  if (classMatch == null) return null;
  final className = classMatch.group(1)!;

  final domainMatch = RegExp(r'ThemeDomain\.(\w+)').firstMatch(source);
  if (domainMatch == null) return null;
  final domain = domainMatch.group(1)!;

  final normalized = filePath.replaceAll('\\', '/');
  final libIndex = normalized.indexOf('lib/');
  final relativePath = libIndex >= 0
      ? normalized.substring(libIndex + 'lib/'.length)
      : normalized;
  final importPath = 'package:flutter_application_1/$relativePath';

  return _ThemeEntry(
    className: className,
    domain: domain,
    importPath: importPath,
  );
}

// ---------------------------------------------------------------------------
// 1. 生成 .g.dart（无 import，纯声明）
// ---------------------------------------------------------------------------

Future<void> _writeGeneratedFile(List<_ThemeEntry> entries) async {
  String list(String domain) {
    final items = entries
        .where((e) => e.domain == domain)
        .map((e) => '  ${e.className}(),')
        .join('\n');
    return items.isEmpty ? '' : items;
  }

  final timestamp = DateTime.now().toIso8601String();

  final content =
      '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/theme_registry_gen.dart at $timestamp
// Run: dart run tool/theme_registry_gen.dart

part of 'theme_catalog.dart';

// --------------------------------------------------------------------------
// 域分类列表（imports 在主库 theme_catalog.dart 中维护）
// --------------------------------------------------------------------------

const List<AppTheme> _universalThemes = [
${list('universal')}
];

const List<AppTheme> _maimaiThemes = [
${list('maimai')}
];

const List<AppTheme> _chunithmThemes = [
${list('chunithm')}
];

// --------------------------------------------------------------------------
// 全局字典 (themeId → AppTheme instance)
// --------------------------------------------------------------------------

Map<String, AppTheme> _buildAllThemesRegistry() => {
  for (final t in [..._universalThemes, ..._maimaiThemes, ..._chunithmThemes])
    t.themeId: t,
};

// --------------------------------------------------------------------------
// 自动选取的全局默认主题（取 universalThemes 第一项）
// --------------------------------------------------------------------------

AppTheme get _defaultTheme => _universalThemes.first;
''';

  final outFile = File('lib/ui/design_system/theme/theme_catalog.g.dart');
  await outFile.writeAsString(content);
}

// ---------------------------------------------------------------------------
// 2. 刷新 theme_catalog.dart 中的 BEGIN/END import 锚区段
// ---------------------------------------------------------------------------

Future<void> _refreshCatalogImports(List<_ThemeEntry> entries) async {
  final catalogFile = File('lib/ui/design_system/theme/theme_catalog.dart');
  final source = await catalogFile.readAsString();

  const begin = '// AUTO-IMPORTS BEGIN';
  const end = '// AUTO-IMPORTS END';

  final newImports = entries.map((e) => "import '${e.importPath}';").join('\n');

  final replacement = '$begin\n$newImports\n$end';

  String updated;
  if (source.contains(begin) && source.contains(end)) {
    // 替换锚区段
    final startIdx = source.indexOf(begin);
    final endIdx = source.indexOf(end) + end.length;
    updated =
        source.substring(0, startIdx) + replacement + source.substring(endIdx);
  } else {
    // 首次运行，插入至 part 声明之后
    updated = source.replaceFirst(
      "part 'theme_catalog.g.dart';",
      "part 'theme_catalog.g.dart';\n\n$replacement",
    );
  }

  await catalogFile.writeAsString(updated);
}
